### ISSUE TITLE
Spike on HTTPoison

### ISSUE THREAD

**Issue by ZooeyMiller** [finnhodgkin/phoenix-auth-github#2]
We need to spike on HTTPoison to look into making HTTP requests to github with elixir.

**Comment by ZooeyMiller** [comment]
On github: https://github.com/edgurgel/httpoison

On hexdocs: https://hexdocs.pm/httpoison/api-reference.html

**Comment by finnhodgkin** [comment]
Worth checking Tudo to see how mocking was implemented with HTTPoison:

https://github.com/dwyl/tudo

**Comment by ZooeyMiller** [comment]
So HTTPoison has a very simple and nice API.
```elixir
  def get_stuff(string) do
    HTTPoison.get!(string)
    |> Map.get(:body)
  end
```
works for a get request, but returns the JSON as a string, the next step is working out how to parse the JSON into a map.

**Comment by finnhodgkin** [comment]
Yeah, it just works. Poison seems to be the favourite JSON decoder.

**Comment by finnhodgkin** [comment]
On github: https://github.com/devinus/poison

On hexdocs: https://hexdocs.pm/poison/api-reference.html

**Comment by ZooeyMiller** [comment]
We can use [Poison](https://github.com/devinus/poison) to parse the JSON.
```elixir
  def get_stuff(string) do
    HTTPoison.get!(string)
    |> Map.get(:body)
    |> Poison.decode!
  end
```
This will take JSON as a string and return it as a map.

**Comment by finnhodgkin** [comment]
```elixir
%{body: body} = 
      HTTPoison.get!("https://api.sunrise-sunset.org/json?lat=36.7201600&lng=-4.4203400")
%{"results" => %{ "sunrise" => sunrise}} = 
      body
      |> Poison.decode!

# sunrise == "6:16:55 AM"
```

**Comment by finnhodgkin** [comment]
Again, it just works :heart:

**Comment by finnhodgkin** [comment]
For mocking we can just use the same setup as Tudo. It worked great, and was really easy to set up and add to: https://github.com/dwyl/tudo/blob/master/web/httpoison/in_memory.ex

**Comment by ZooeyMiller** [comment]
Yep, the InMemory solution will work nicely, here's the original article explaining it http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/

**Comment by ZooeyMiller** [comment]
Set up in a wee practice exactly as described above and the mocking works perfectly :ok_hand:
